[package]
name = "zoa_test"
version = "0.1.0"
authors = ["Delphix"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
azure_core = "0.1.1"
azure_identity = "0.1.1"
azure_storage = "0.1.0"
azure_storage_blobs = "0.1.0"
chrono = "0.4.19"
clap = { version = "3.1.6", features = ["derive"] }
futures = "0.3.13"
git-version = "0.3.5"
itertools = "0.10.3"
lazy_static = "1.4.0"
nvpair = { git = "https://github.com/delphix/rust-libzfs"}
rand = "0.8.3"
rusoto_core = "0.48.0"
rusoto_credential = "0.48.0"
rusoto_s3 = "0.48.0"
rusoto_sts = "0.48.0"
semver = "1.0.4"
serde = { version = "1.0.125", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0.64"
tokio = { version = "1.4", features = ["full"] }
util = { path = "../util" }
zettacache = { path = "../zettacache" }
zettaobject = { path = "../zettaobject" }
