[package]
name = "zcache"
version = "0.1.0"
authors = ["Delphix"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
async-trait = "0.1.51"
clap={version="3.1.6",features=["derive"]}
exitcode = "1.1.2"
git-version = "0.3.5"
humantime = "2.1.0"
log = "0.4"
more-asserts = "0.2.1"
num-traits = "0.2.14"
nvpair = { git = "https://github.com/delphix/rust-libzfs"}
semver = "1.0.4"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
termsize = "0.1.6"
tokio = { version = "1.4", features = ["full"] }
util = { path = "../util" }
