#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# This run file contains all of the common functional tests.  When
# adding a new test consider also adding it to the sanity.run file
# if the new test runs to completion in only a few seconds.
#
# Approximate run time: 4-5 hours
#

[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 600
post_user = root
post = cleanup
failsafe_user = root
failsafe = callbacks/zfs_failsafe
outputdir = /var/tmp/test_results
tags = ['functional']

[tests/functional/acl/off]
tests = ['posixmode']
tags = ['functional', 'acl']

[tests/functional/acl/posix:Linux]
tests = ['posix_001_pos', 'posix_002_pos', 'posix_003_pos', 'posix_004_pos']
tags = ['functional', 'acl', 'posix']

[tests/functional/acl/posix-sa:Linux]
tests = ['posix_001_pos', 'posix_002_pos', 'posix_003_pos', 'posix_004_pos']
tags = ['functional', 'acl', 'posix-sa']

# -------------------------------------------------------------
# TODO: Pool checkpoint functionality hasn't been implemented yet. Uncomment the
# below section once its done.
# -------------------------------------------------------------
# [tests/functional/pool_checkpoint]
# tests = ['checkpoint_after_rewind', 'checkpoint_big_rewind',
#     'checkpoint_capacity', 'checkpoint_conf_change', 'checkpoint_discard',
#     'checkpoint_discard_busy', 'checkpoint_discard_many',
#     'checkpoint_indirect', 'checkpoint_invalid', 'checkpoint_lun_expsz',
#     'checkpoint_open', 'checkpoint_removal', 'checkpoint_rewind',
#     'checkpoint_ro_rewind', 'checkpoint_sm_scale', 'checkpoint_twice',
#     'checkpoint_vdev_add', 'checkpoint_zdb', 'checkpoint_zhack_feat']
# tags = ['functional', 'pool_checkpoint']
# timeout = 1800

[tests/functional/chattr]
tests = ['chattr_001_pos', 'chattr_002_neg']
tags = ['functional', 'chattr']

[tests/functional/cp_files]
tests = ['cp_files_001_pos']
tags = ['functional', 'cp_files']

[tests/functional/atime]
tests = ['atime_001_pos', 'atime_002_neg', 'atime_003_pos',
   'root_atime_off', 'root_atime_on', 'root_relatime_on']
tags = ['functional', 'atime']

[tests/functional/ctime]
tests = ['ctime_001_pos']
tags = ['functional', 'ctime']

[tests/functional/exec]
tests = ['exec_001_pos', 'exec_002_neg']
tags = ['functional', 'exec']

[tests/functional/fallocate]
tests = ['fallocate_prealloc', 'fallocate_punch-hole']
tags = ['functional', 'fallocate']

[tests/functional/mount]
tests = ['umount_001', 'umountall_001', 'umount_unlinked_drain']
tags = ['functional', 'mount']

[tests/functional/suid]
tests = ['suid_write_to_none', 'suid_write_to_sgid',
	'suid_write_to_suid', 'suid_write_to_suid_sgid']
tags = ['functional', 'suid']

[tests/functional/cli_root/zfs]
tests = ['zfs_001_neg', 'zfs_002_pos', 'zfs_003_neg']
tags = ['functional', 'cli_root', 'zfs']

[tests/functional/cli_root/zfs_bookmark]
tests = ['zfs_bookmark_cliargs']
tags = ['functional', 'cli_root', 'zfs_bookmark']

[tests/functional/cli_root/zfs_change-key]
tests = ['zfs_change-key.ksh', 'zfs_change-key_child.ksh', 'zfs_change-key_clones.ksh',
	'zfs_change-key_format.ksh', 'zfs_change-key_inherit.ksh', 'zfs_change-key_load.ksh',
	'zfs_change-key_location.ksh', 'zfs_change-key_pbkdf2iters.ksh']
tags = ['functional', 'cli_root', 'zfs_change-key']

# -------------------------------------------------------------
# TODO: Add the following tests back after relevant bug fixes.
# zpool_create_018_pos - DOSE-550
# zpool_create_encrypted - DOSE-550
# zpool_create_features_002_pos - DOSE-550
# zpool_create_features_003_pos - DOSE-550
# zpool_create_features_006_pos - DOSE-550
# zpool_create_features_009_pos - DOSE-550
# zpool_create_024_pos - DOSE-568
# -------------------------------------------------------------
# TODO: zpool_create_003_pos fails because of DOSE-545. Its not creating a
# panic, hence, keeping it in the suite.
# -------------------------------------------------------------
[tests/functional/cli_root/zpool_create]
tests = ['zpool_create_001_pos', 'zpool_create_002_pos',
	'zpool_create_003_pos', 'zpool_create_004_pos', 'zpool_create_005_pos',
	'zpool_create_006_pos', 'zpool_create_007_neg', 'zpool_create_008_pos',
	'zpool_create_009_neg', 'zpool_create_010_neg', 'zpool_create_011_neg',
	'zpool_create_012_neg', 'zpool_create_014_neg', 'zpool_create_015_neg',
	'zpool_create_017_neg', 'zpool_create_019_pos',
	'zpool_create_020_pos', 'zpool_create_021_pos', 'zpool_create_022_pos',
	'zpool_create_023_neg', 'zpool_create_crypt_combos',
	'zpool_create_draid_001_pos', 'zpool_create_draid_002_pos',
	'zpool_create_draid_003_pos', 'zpool_create_draid_004_pos',
	'zpool_create_features_001_pos', 'zpool_create_features_004_neg',
	'zpool_create_features_005_pos',
	'zpool_create_features_007_pos', 'zpool_create_features_008_pos',
	'create-o_ashift',
	'zpool_create_tempname', 'zpool_create_dryrun_output']
tags = ['functional', 'cli_root', 'zpool_create']
