[package]
name = "zoa"
version = "0.1.0"
authors = ["Delphix"]
edition = "2021"
build = "src/build.rs"

[build-dependencies]
cbindgen = "0.20"

[lib]
crate-type = ["cdylib"]      # Creates dynamic lib

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path =  "../util" }
zettacache = { path =  "../zettacache" }
zettaobject = { path =  "../zettaobject" }
