#!/bin/bash

#
# This script starts the ZFS Object Agent process.
# It uses the following environment variables, typically set by zfs-object-agent.service
# to determine which command line parameters to pass to the ZFS Object Agent process.
#  - ZOA_CONFIG: Configuration file to set tunables (toml/json/yaml)
#  - ZOA_LOG_CONFIG : log4rs configuration
#  - ZETTACACHE_DIRECTORY: Directory to use for ZettaCache device discovery.
#

#
# Wait for the agent to start listening to requests. This function
# will loop until "zcache list" can communicate with the agent or
# systemd times out the service.
#
function wait_for_agent()
{
	start=$SECONDS
	while :; do
		zcache list
		if [[ $? -eq 0 ]]; then
			echo "Succeded in: $((SECONDS - start)) seconds"
			return
		fi
		echo "Elapsed wait time: $((SECONDS - start)) seconds"
	done
}

ZOA_LOG_CONFIG="${ZOA_LOG_CONFIG:-/etc/zfs/zoa_log4rs.yml}"
PARAMS="-l ${ZOA_LOG_CONFIG} --clear-incompatible-cache"
echo "Logging config: ${ZOA_LOG_CONFIG}"

if [[ ! -z $ZOA_CONFIG ]]; then
	echo "Config file: ${ZOA_CONFIG}"
	PARAMS="${PARAMS} -t ${ZOA_CONFIG}"
fi
PARAMS="$PARAMS -d ${ZETTACACHE_DIRECTORY:-/dev}"

/sbin/zfs_object_agent ${PARAMS} &
wait_for_agent
