use core::time::Duration;
use std::collections::HashMap;
use std::error::Error;
use std::fmt::Display;
use std::iter;
use std::marker::Send;
use std::ops::Range;
use std::pin::Pin;
use std::sync::Arc;
use std::time::Instant;

use anyhow::Result;
use async_trait::async_trait;
use bytes::Bytes;
use chrono::DateTime;
use chrono::FixedOffset;
use futures::stream;
use futures::Future;
use futures::FutureExt;
use futures::Stream;
use futures::StreamExt;
use http::Response;
use http::StatusCode;
use lazy_static::lazy_static;
use log::trace;
use log::*;
use rand::prelude::*;
use rusoto_core::ByteStream;
use serde::Deserialize;
use serde::Deserializer;
use serde::Serialize;
use tokio::time::error::Elapsed;
use util::measure;
use util::tunable;
use util::with_alloctag;

use crate::access_stats::ObjectAccessOpType;
use crate::access_stats::StatMapValue;
use crate::object_access::blob::BlobBucketAccess;
use crate::object_access::blob::BlobObjectAccess;
use crate::object_access::s3::S3BucketAccess;
use crate::object_access::s3::S3ObjectAccess;

pub mod blob;
pub mod s3;

lazy_static! {
    static ref NON_RETRYABLE_ERRORS: Vec<StatusCode> = vec![
        StatusCode::BAD_REQUEST,
        StatusCode::FORBIDDEN,
        StatusCode::NOT_FOUND,
        StatusCode::METHOD_NOT_ALLOWED,
        StatusCode::PRECONDITION_FAILED,
        StatusCode::PAYLOAD_TOO_LARGE,
        StatusCode::RANGE_NOT_SATISFIABLE,
    ];
}

tunable! {
    // log operations that take longer than this with info!()
    static ref LONG_OPERATION_DURATION: Duration = Duration::from_secs(2);
    static ref XLONG_OPERATION_DURATION: Duration = Duration::from_secs(60);
    static ref PANIC_ON_XLONG_OPERATION: bool = false;
    pub static ref OBJECT_DELETION_BATCH_SIZE: usize = 1000;
    static ref PER_REQUEST_TIMEOUT: Duration = Duration::from_secs(2);
}

#[derive(Debug)]
pub struct GetError(String);

impl Display for GetError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}
impl Error for GetError {}

#[derive(Debug)]
pub struct PutError {}

impl Display for PutError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("put error")
    }
}
impl Error for PutError {}

#[derive(Debug)]
pub enum ObjectStoreError {
    NoSuchKey,
    Other(String),
}

impl Display for ObjectStoreError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ObjectStoreError::NoSuchKey => f.write_str("no such key"),
            ObjectStoreError::Other(message) => write!(f, "error: {}", message),
        }
    }
}
impl Error for ObjectStoreError {}

#[derive(Debug)]
pub struct ObjectStat {
    pub last_modified: Option<DateTime<FixedOffset>>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum S3Credentials {
    /// Get credentials from the following sources in order:
    /// 1. Environment variables
    /// 2. AWS credentials file
    /// 3. IAM instance profile.
    Automatic,
    /// Read credentials from a profile in an ini file
    Profile(String),
    /// Credentials specified as parameters
    Key {
        aws_access_key_id: String,
        aws_secret_access_key: String,
    },
    /// AWS IAM roles passed using an instance profile
    InstanceProfile,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum BlobCredentials {
    /// Get credentials the following sources in order:
    /// 1. Environment variables
    /// 2. ~/.azure/credentials file
    /// 3. managed identities.
    Automatic,
    /// Read credentials from a profile in an ini file
    Profile(String),
    /// Credentials specified as parameters
    Key {
        azure_account: String,
        azure_key: String,
    },
    /// Managed identities
    ManagedCredentials { azure_account: String },
}

#[derive(Serialize, Debug, Clone)]
#[serde(tag = "protocol", rename_all = "lowercase")]
pub enum ObjectAccessProtocol {
    S3 {
        endpoint: String,
        region: String,
        credentials: S3Credentials,
    },
    Blob {
        credentials: BlobCredentials,
    },
}

impl<'de> Deserialize<'de> for ObjectAccessProtocol {
    /// This exists to provide transparent upgrades from older on-disk and wire-format messages that
    /// didn't contain the protocol string. When using this to deserialize, serde will first
    /// attempt to deserialize using what would the autogenerated implementation of Deserialize.
    /// This will deserialize a struct written out using the latest version, which is internally
    /// tagged with "protocol". If it can't find the tag or one of the variant's fields, it will
    /// fail to deserialize, and fall back to attempting to deserialize the S3Legacy struct,
    /// which has the necessary information to create an S3 Protocol struct, but was written by
    /// something without protocol tag support.
    fn deserialize<D>(d: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize, Debug)]
        #[serde(tag = "protocol", rename_all = "lowercase")]
        pub enum New {
            S3 {
                endpoint: String,
                region: String,
                credentials: S3Credentials,
            },
            Blob {
                credentials: BlobCredentials,
            },
        }

        #[derive(Deserialize, Debug)]
        #[serde(untagged)]
        enum Upgrader {
            New(New),
            S3Legacy {
                endpoint: String,
                region: String,
                #[serde(alias = "profile")]
                credentials_profile: Option<String>,
            },
        }

        match Upgrader::deserialize(d)? {
            Upgrader::New(New::S3 {
                endpoint,
                region,
                credentials,
            }) => Ok(Self::S3 {
                endpoint,
                region,
                credentials,
            }),
            Upgrader::New(New::Blob { credentials }) => Ok(Self::Blob { credentials }),
            Upgrader::S3Legacy {
                endpoint,
                region,
                credentials_profile,
            } => Ok(Self::S3 {
                endpoint,
                region,
                credentials: match credentials_profile {
                    Some(profile) => S3Credentials::Profile(profile),
                    None => S3Credentials::Automatic,
                },
            }),
        }
    }
}

enum ObjectAccessEnum {
    S3(S3ObjectAccess),
    Blob(BlobObjectAccess),
}

pub struct ObjectAccess {
    // XXX we can probably replace this with `Box<dyn ObjectAccessTrait>`
    inner: ObjectAccessEnum,
    readonly: bool,
}

impl ObjectAccess {
    pub async fn new(
        protocol: ObjectAccessProtocol,
        bucket: String,
        readonly: bool,
    ) -> Result<Arc<Self>> {
        match protocol {
            ObjectAccessProtocol::S3 {
                endpoint,
                region,
                credentials,
            } => Ok(ObjectAccess::from_s3(
                S3ObjectAccess::new(&endpoint, &region, &bucket, credentials),
                readonly,
            )),
            ObjectAccessProtocol::Blob { credentials } => {
                let oa = BlobObjectAccess::new(&bucket, credentials).await?;
                Ok(ObjectAccess::from_blob(oa, readonly))
            }
        }
    }

    fn from_s3(oa: S3ObjectAccess, readonly: bool) -> Arc<Self> {
        Arc::new(ObjectAccess {
            inner: ObjectAccessEnum::S3(oa),
            readonly,
        })
    }

    fn from_blob(oa: BlobObjectAccess, readonly: bool) -> Arc<Self> {
        Arc::new(ObjectAccess {
            inner: ObjectAccessEnum::Blob(oa),
            readonly,
        })
    }

    pub fn readonly(&self) -> bool {
        self.readonly
    }

    pub fn bucket(&self) -> String {
        match &self.inner {
            ObjectAccessEnum::S3(oa) => oa.bucket(),
            ObjectAccessEnum::Blob(oa) => oa.bucket(),
        }
    }

    pub fn region(&self) -> Option<String> {
        match &self.inner {
            ObjectAccessEnum::S3(oa) => Some(oa.region()),
            ObjectAccessEnum::Blob(_) => None,
        }
    }

    pub fn endpoint(&self) -> Option<String> {
        match &self.inner {
            ObjectAccessEnum::S3(oa) => Some(oa.endpoint()),
            ObjectAccessEnum::Blob(_) => None,
        }
    }

    pub fn credentials_profile(&self) -> Option<String> {
        match &self.inner {
            ObjectAccessEnum::S3(oa) => oa.credentials_profile(),
            ObjectAccessEnum::Blob(oa) => oa.credentials_profile(),
        }
    }

    pub fn protocol(&self) -> ObjectAccessProtocol {
        match &self.inner {
            ObjectAccessEnum::S3(oa) => ObjectAccessProtocol::S3 {
                endpoint: oa.endpoint(),
                region: oa.region(),
                credentials: match oa.credentials_profile() {
                    Some(profile) => S3Credentials::Profile(profile),
                    None => S3Credentials::Automatic,
                },
            },
            ObjectAccessEnum::Blob(oa) => ObjectAccessProtocol::Blob {
                credentials: match oa.credentials_profile() {
                    Some(profile) => BlobCredentials::Profile(profile),
                    None => BlobCredentials::Automatic,
                },
            },
        }
    }

    fn as_trait(&self) -> &dyn ObjectAccessTrait {
        match &self.inner {
            ObjectAccessEnum::S3(oa) => oa,
            ObjectAccessEnum::Blob(oa) => oa,
        }
    }

    pub async fn get_object(&self, key: String, stat_type: ObjectAccessOpType) -> Result<Bytes> {
        self.as_trait()
            .get_object(key, stat_type, None)
            .boxed()
            .await
    }

    pub async fn get_object_range(
        &self,
        key: String,
        stat_type: ObjectAccessOpType,
        range: Range<usize>,
    ) -> Result<Bytes> {
        measure!()
            .fut(self.as_trait().get_object(key, stat_type, Some(range)))
            .boxed()
            .await
    }

    pub async fn object_exists(&self, key: String) -> bool {
        self.stat_object(key).await.is_some()
    }

    pub async fn stat_object(&self, key: String) -> Option<ObjectStat> {
        self.as_trait().stat_object(key).await
    }

    pub async fn put_object_stream<F>(
        &self,
        key: String,
        streamfunc: F,
        stat_type: ObjectAccessOpType,
    ) where
        F: Fn() -> (ByteStream, usize) + Send + Sync,
    {
        assert!(!self.readonly);
        self.as_trait()
            .put_object_stream(key.clone(), &streamfunc, stat_type, None)
            .await
            .unwrap();
    }

    async fn put_object_impl(
        &self,
        key: String,
        bytes: Bytes,
        stat_type: ObjectAccessOpType,
        timeout: Option<Duration>,
    ) -> Result<(), OAError<PutError>> {
        self.as_trait()
            .put_object_stream(
                key,
                &|| {
                    let my_bytes = bytes.clone();
                    with_alloctag(
                    "ObjectAccess::put_object_impl() ByteStream::new_with_size() Box::pin(stream)",
                    || {
                        (
                            ByteStream::new_with_size(
                                stream::iter(iter::once(Ok(my_bytes))),
                                bytes.len(),
                            ),
                            bytes.len(),
                        )
                    },
                )
                },
                stat_type,
                timeout,
            )
            .await
    }

    pub async fn put_object(&self, key: String, data: Bytes, stat_type: ObjectAccessOpType) {
        // Note that we need to PutObject before invalidating the cache.  If a
        // get_object() is called while put_object() is in progress, it may see
        // the old or new value, which is fine.  After put_object() returns,
        // get_object() must return the new value.  If we invalidated before the
        // PutObject, a concurrent get_object() could retrieve the old value and
        // add it to the cache, allowing the old value to be read (from the
        // cache) after put_object() returns.
        self.put_object_impl(key.clone(), data, stat_type, None)
            .await
            .unwrap();
    }

    pub async fn put_object_timed(
        &self,
        key: String,
        data: Bytes,
        stat_type: ObjectAccessOpType,
        timeout: Option<Duration>,
    ) -> Result<(), OAError<PutError>> {
        self.put_object_impl(key.clone(), data, stat_type, timeout)
            .await
    }

    pub async fn delete_object(&self, key: String) {
        assert!(!self.readonly);
        self.delete_objects(stream::iter(iter::once(key))).await;
    }

    pub async fn delete_objects<S>(&self, mut stream: S)
    where
        S: Stream<Item = String> + Send + Unpin,
    {
        assert!(!self.readonly);
        self.as_trait().delete_objects(&mut stream).await
    }

    pub fn list_objects(
        &self,
        prefix: String,
        start_after: Option<String>,
        use_delimiter: bool,
    ) -> impl Stream<Item = String> + Send {
        self.as_trait()
            .list(prefix, start_after, use_delimiter, false)
    }

    pub async fn collect_objects(
        &self,
        prefix: String,
        start_after: Option<String>,
    ) -> Vec<String> {
        self.list_objects(prefix, start_after, true).collect().await
    }

    pub fn list_prefixes(&self, prefix: String) -> impl Stream<Item = String> {
        self.as_trait().list(prefix, None, true, true)
    }

    pub fn collect_stats(&self) -> HashMap<String, StatMapValue> {
        self.as_trait().collect_stats()
    }
}

enum BucketAccessEnum {
    S3(S3BucketAccess),
    Azure(BlobBucketAccess),
}

pub struct BucketAccess {
    inner: BucketAccessEnum,
}

impl BucketAccess {
    pub async fn new(protocol: ObjectAccessProtocol) -> Result<Arc<Self>> {
        match protocol {
            ObjectAccessProtocol::S3 {
                endpoint,
                region,
                credentials,
            } => {
                let ba = S3BucketAccess::new(&endpoint, &region, credentials)?;
                Ok(Arc::new(BucketAccess {
                    inner: BucketAccessEnum::S3(ba),
                }))
            }
            ObjectAccessProtocol::Blob { credentials } => {
                let ba = BlobBucketAccess::new(credentials).await?;
                Ok(Arc::new(BucketAccess {
                    inner: BucketAccessEnum::Azure(ba),
                }))
            }
        }
    }

    fn as_trait(&self) -> &dyn BucketAccessTrait {
        match &self.inner {
            BucketAccessEnum::S3(oa) => oa,
            BucketAccessEnum::Azure(oa) => oa,
        }
    }

    pub async fn list_buckets(&self) -> Vec<String> {
        self.as_trait().list_buckets().await
    }
}

#[async_trait]
pub trait BucketAccessTrait: Send + Sync {
    async fn list_buckets(&self) -> Vec<String>;
}

#[async_trait]
pub trait ObjectAccessTrait: Send + Sync {
    fn list(
        &self,
        prefix: String,
        start_after: Option<String>,
        use_delimiter: bool,
        list_prefixes: bool,
    ) -> Pin<Box<dyn Stream<Item = String> + Send>>;

    async fn get_object(
        &self,
        key: String,
        stat_type: ObjectAccessOpType,
        range: Option<Range<usize>>,
    ) -> Result<Bytes>;

    async fn stat_object(&self, key: String) -> Option<ObjectStat>;

    async fn put_object_stream(
        &self,
        key: String,
        // We unfortunately can't take the ByteStream directly because we may
        // need to iterate it multiple times, if we need to retry.  streamfunc
        // returns (stream, stream_len_bytes).
        streamfunc: &(dyn Fn() -> (ByteStream, usize) + Send + Sync),
        stat_type: ObjectAccessOpType,
        timeout: Option<Duration>,
    ) -> Result<(), OAError<PutError>>;

    async fn delete_objects(&self, stream: &mut (dyn Stream<Item = String> + Send + Unpin));

    fn collect_stats(&self) -> HashMap<String, StatMapValue>;
}

#[derive(Debug)]
pub enum RequestError<E: Display> {
    /// A service-specific error occurred.
    Service(E),
    /// An unknown http error occurred.  The raw HTTP response is provided.
    Unknown(Response<Bytes>),
    /// An error occurred dispatching the HTTP request or processing the response
    InternalError(String),
    /// An error was encountered while the fetching Credentials. This generally is
    /// an error from one of the underlying libraries used by rusoto that is wrapped
    /// up with this type.
    Credentials(String),
    /// The credentials in use have expired
    ExpiredCredentials,
    /// The credentials in use are not valid
    InvalidCredentials,
    /// The request time and the server time were too far out of sync
    TimeSkew,
}

impl<E: Display> Display for RequestError<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RequestError::Service(e) => e.fmt(f),
            RequestError::Unknown(r) => f.write_str(std::str::from_utf8(r.body()).unwrap()),
            RequestError::InternalError(s) => s.fmt(f),
            RequestError::Credentials(s) => s.fmt(f),
            RequestError::ExpiredCredentials => f.write_str("Expired credentials"),
            RequestError::InvalidCredentials => f.write_str("Invalid credentials"),
            RequestError::TimeSkew => f.write_str("Request time too skewed"),
        }
    }
}

impl<E: Display> From<std::io::Error> for RequestError<E> {
    fn from(err: std::io::Error) -> Self {
        Self::InternalError(err.to_string())
    }
}

#[derive(Debug)]
#[allow(clippy::upper_case_acronyms)]
pub enum OAError<E: Display> {
    TimeoutError(Elapsed),
    RequestError(RequestError<E>),
    Other(anyhow::Error),
}

impl<E> Display for OAError<E>
where
    E: std::error::Error + 'static,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            OAError::TimeoutError(e) => e.fmt(f),
            OAError::RequestError(e) => e.fmt(f),
            OAError::Other(e) => e.fmt(f),
        }
    }
}

impl<E> Error for OAError<E> where E: std::error::Error + 'static {}

async fn retry_impl<F, O, E>(
    msg: &str,
    timeout_opt_initial: Option<Duration>,
    f: impl Fn() -> F,
) -> Result<O, OAError<E>>
where
    E: Error + 'static,
    F: Future<Output = Result<O, OAError<E>>>,
{
    let mut time_skew_retried = false;
    let mut expired_token_retried = false;
    let mut delay = Duration::from_secs_f64(thread_rng().gen_range(0.001..0.2));
    let mut timeout_opt = timeout_opt_initial;
    loop {
        let begin = Instant::now();
        let result = match timeout_opt {
            Some(timeout) => match tokio::time::timeout(timeout, f()).await {
                Err(e) => Err(OAError::TimeoutError(e)),
                Ok(res2) => res2,
            },
            None => f().await,
        };
        let e = match result {
            res @ Ok(_) => return res,
            res @ Err(OAError::RequestError(RequestError::Service(_))) => return res,
            res @ Err(OAError::RequestError(RequestError::Credentials(_))) => return res,
            res @ Err(OAError::RequestError(RequestError::InvalidCredentials)) => return res,
            res @ Err(OAError::RequestError(RequestError::ExpiredCredentials)) => {
                let elapsed = begin.elapsed();
                // Tokens are refreshed on expiry. But if a request is delivered late, the
                // token might have expired by the time it is processsed. We retry once in
                // the event of this error.
                if !expired_token_retried {
                    info!(
                        "Retrying on ExpiredToken error; request took {} secs.",
                        elapsed.as_secs()
                    );
                    expired_token_retried = true;
                    continue;
                } else {
                    error!(
                        "ExpiredToken error hit repeatedly; request took {} secs.",
                        elapsed.as_secs()
                    );
                    return res;
                }
            }
            res @ Err(OAError::RequestError(RequestError::TimeSkew)) => {
                let elapsed = begin.elapsed();
                // If the request is delivered late, it is rejected by the S3 server. In the
                // event of this error, a request is retried. If the system time is too
                // skewed (15 minutes for Amazon S3), requests will get rejected repeatedly
                // and will never succeed. To avoid this, we retry just once and then give
                // up.
                if !time_skew_retried {
                    info!(
                        "Retrying on RequestTimeTooSkewed error; request took {} secs.",
                        elapsed.as_secs()
                    );
                    time_skew_retried = true;
                    continue;
                } else {
                    error!(
                        "RequestTimeTooSkewed error hit repeatedly; request took {} secs.",
                        elapsed.as_secs()
                    );
                    return res;
                }
            }
            Err(OAError::RequestError(RequestError::Unknown(bhr))) => {
                if NON_RETRYABLE_ERRORS.contains(&bhr.status()) {
                    return Err(OAError::RequestError(RequestError::Unknown(bhr)));
                }
                OAError::RequestError(RequestError::Unknown(bhr))
            }
            Err(e @ OAError::TimeoutError(_)) => {
                timeout_opt = timeout_opt
                    .map(|d| d.checked_mul(2).unwrap_or_else(|| Duration::from_secs(60)));
                e
            }
            Err(e) => e,
        };
        debug!(
            "{} returned: {}; retrying in {}ms",
            msg,
            e,
            delay.as_millis()
        );
        if delay > *LONG_OPERATION_DURATION {
            info!(
                "long retry: {} returned: {}; retrying in {:?}",
                msg, e, delay
            );
        }
        tokio::time::sleep(delay).await;
        delay = delay.mul_f64(thread_rng().gen_range(1.5..2.5));
    }
}

/// `timeout_opt` controls whether the overall request will be cancelled after a certain amount
/// of time. This is useful for requests that have complex retry logic or need to complete
/// quickly for correctness reasons.  If a timeout is not specified, a default per-request
/// timeout will be used. This helps avoid problems where the object store backend drops some
/// requests on the floor. This per-request timeout will be retried indefinitely, so
/// Err(TimeoutError) doesn't need to be handled gracefully unless `timeout_opt` is specified.
async fn retry<F, O, E>(
    msg: &str,
    timeout_opt: Option<Duration>,
    f: impl Fn() -> F,
) -> Result<O, OAError<E>>
where
    E: Error + 'static,
    F: Future<Output = Result<O, OAError<E>>>,
{
    trace!("{}: begin", msg);
    let begin = Instant::now();
    // Because of the `xor` here, exactly one of timeout_opt and retry_timeout_opt will be None and
    // the other will be Some.
    let retry_timeout_opt = timeout_opt.xor(Some(*PER_REQUEST_TIMEOUT));
    let result = match timeout_opt {
        Some(timeout) => {
            match tokio::time::timeout(timeout, retry_impl(msg, retry_timeout_opt, f)).await {
                Err(e) => Err(OAError::TimeoutError(e)),
                Ok(res2) => res2,
            }
        }
        None => retry_impl(msg, retry_timeout_opt, f).await,
    };
    let elapsed = begin.elapsed();
    trace!("{}: returned in {}ms", msg, elapsed.as_millis());

    if elapsed > *XLONG_OPERATION_DURATION && *PANIC_ON_XLONG_OPERATION {
        panic!(
            "extremely long operation: {}, returned in {:.1}s",
            msg,
            elapsed.as_secs_f64()
        );
    } else if elapsed > *LONG_OPERATION_DURATION {
        info!(
            "long completion: {}: returned in {:.1}s",
            msg,
            elapsed.as_secs_f64()
        );
    }
    result
}
