name: checkstyle

on:
  push:
  pull_request:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo xargs --arg-file=${{ github.workspace }}/.github/workflows/build-dependencies.txt apt-get install -qq
        sudo apt-get install -qq mandoc cppcheck pax-utils devscripts
        sudo python3 -m pip install --quiet flake8
        sudo apt-get clean

        # confirm that the tools are installed
        # the build system doesn't fail when they are not
        checkbashisms --version
        cppcheck --version
        flake8 --version
        scanelf --version
        shellcheck --version
    - name: Install nightly rustfmt
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
    - name: Prepare
      run: |
        ./autogen.sh
        ./configure
        make -j$(nproc) --no-print-directory --silent
    - name: Codecheck
      run: |
        make -j$(nproc) --no-print-directory --silent codecheck
    - name: Lint
      run: |
        make -j$(nproc) --no-print-directory --silent lint
